version: 2
python:
   version: 3.7
   install:
      - requirements: docs/source/requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
   system_packages: true
sphinx:
  builder: html
  configuration: docs/source/conf.py